#type: args

train:
  epochs: 200
  batch_size: 16
  lr: 1.0e-2
  valid_epoch_interval: 5
  is_lr_decay: true

diffusion:
  layers: 2
  channels: 1
  nheads: 1
  diffusion_embedding_dim: 64
  beta_start: 0.0001
  beta_end: 0.2
  num_steps: 100
  schedule: "quad"
  is_adp: true
  proj_t: 8
  is_cross_t: true
  is_cross_s: true

model:
  is_unconditional: 0
  timeemb: 64
  featureemb: 8
  target_strategy: "hybrid"
  use_guide: true
  mask_sensor: []
