all:
	g++ -O3 -o cmake-build-debug/incCD -Wall -Wextra -Werror -pedantic -std=c++14 main.cpp LinearAlgebra/Vector.cpp LinearAlgebra/Matrix.cpp Testing.cpp LinearAlgebra/CentroidDecomposition.cpp MatrixReadWrite.cpp Performance/Benchmark.cpp LinearAlgebra/SVDecomposition.cpp LinearAlgebra/MissingValueRecovery.cpp Statistics/CorrelationMatrix.cpp LinearAlgebra/MissingBlock.cpp

clean:
	rm cmake-build-debug/incCD
